# -*- coding: utf-8 -*-
"""drivers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UXogqepDwU-HA_1tcAm3O0_ClF8i1UDw
"""

#Not a standard class written to implement swich blocks
class switch(object):
    def __init__(self, value):
        self.value = value  # the value we will look for
        self.fall = False   # For empty case blocks

    def __iter__(self):     # to be used in the for loop
        """ Returns once the match method and terminates """
        yield self.match
        raise StopIteration

    def match(self, *args):
        """ Indicates whether to enter the test version """
        if self.fall or not args:
            # an empty argument list means the last case block
            # fall means that the condition triggered earlier and you have to enter 
            #   in each case until the first break
            return True
        elif self.value in args:
            self.fall = True
            return True
        return False

Alc = int(input("Is there any alcohol in the blood?(0 - yes, 1 - no) "))#complite

for case in switch(Alc):
    if case(0): #Alcohol Related
      Alc_Grade = 0
      p1 = 0.073800738
      #print('Alc_Grade = ', Alc_Grade) #Not important part, can be deleted to save memory
      #print('p1 = ', p1) #Not important part, can be deleted to save memory
      break
    if case(1): #NonAlcohol Related
      Alc_Grade = 4
      p1 = 0
      #print('Alc_Grade = ', Alc_Grade) #Not important part, can be deleted to save memory
      #print('p1 = ', p1) #Not important part, can be deleted to save memory
    break

TXT = int(input("Do you write messages when you drive a car??(0 - yes, 1 - no) "))#complite

for case in switch(TXT):
    if case(0): #The driver writes
      TXT_Grade = 0
      p2 = 2.65
      #print('TXT_Grade = ', TXT_Grade) #Not important part, can be deleted to save memory
      #print('p2 = ', p2) #Not important part, can be deleted to save memory
      break
    if case(1): #The driver does not write
      TXT_Grade = 4
      p2 = 0
      #print('TXT_Grade = ', TXT_Grade) #Not important part, can be deleted to save memory
      #print('p2 = ', p2) #Not important part, can be deleted to save memory
    break

RD = int(input("Do you drive aggressively or do you obey all the rules of the road? (0 - I drive aggressively, 1 - I am a calm driver) "))#complite

for case in switch(RD):
    if case(0): #Aggressive driving
      RD_Grade = 0
      p3 = 0.03278688524
      break
    if case(1): #Reckless driving/Tailgatin
      RD_Grade = 4
      p3 = 0.02446782481
      break

Seat = int(input("Do you wear seat belts? (0 - no, 1 - yes) "))#complite
for case in switch(Seat):
    if case(0): #Seatbelts are off
      Seat_Grade = 0
      break
    if case(1): #Seatbelts are on
      Seat_Grade = 4
      break

Speed = int(input("How much do you exceed the speed limit? "))

if Speed > 50:
  Speed = 0
elif Speed > 40:
  Speed = 1
elif Speed > 30:
  Speed = 2
elif Speed > 20:
  Speed = 3
elif Speed > 10:
  Speed = 4
elif Speed == 0:
  Speed = 5
  
for case in switch(Speed):
    if case(0): #More then 50MPH
      Speed_Grade = 0
      p4 = 0.05854800936
      break
    if case(1): #+40MPH
      Speed_Grade = 1
      p4 = 0.02562131693
      break
    if case(2): #+30MPH
      Speed_Grade = 2
      p4 = 0.01999200319
      break
    if case(3): #+20MPH
      Speed_Grade = 3
      p4 = 0.01801477211
      break
    if case(4): #+10MPH
      Speed_Grade = 4
      p4 = 0.0171659085
      break
    if case(5): #Didn't exceed the speed limit
      Speed_Grade = 4
      p4 = 0
      break

Pass = int(input("How many passengers do you have. (0 to 4) "))

for case in switch(Pass):
    if case(0): #0 Passenger
      Pass_Grade = 4
      p5 = 0
      break
    if case(1): #1 Passenger
      Pass_Grade = 3
      p5 = 0.03278688524
      break
    if case(2): #2 Passenger
      Pass_Grade = 2
      p5 = 0.08196721311
      break
    if case(3): #3 Passenger
      Pass_Grade = 1
      p5 = 0.08196721311
      break
    if case(4): #4+ Passenger
      Pass_Grade = 0
      p5 = 0.08196721311
      break

Weat = int(input("Good weather? (0 - yes, 1 - no) "))

for case in switch(Weat):
    if case(0): #Good weather
      p6 = 0
      break
    if case(1): #Bad weather
      p6 = 0.02083333333
      break

Mon = int(input("Number of the month? "))-1

for case in switch(Mon):
    if case(0): #January
      p7 = 0.01369863013
      break
    if case(1): #February
      p7 = 0.01369863013
      break
    if case(2): #March
      p7 = 0.015625
      break
    if case(3): #April
      p7 = 0.015625
      break
    if case(4): #May
      p7 = 0.01785714285
      break
    if case(5): #June
      p7 = 0.01785714285
      break
    if case(6): #July
      p7 = 0.01960784313
      break
    if case(7): #August
      p7 = 0.015625
      break
    if case(8): #September
      p7 = 0.01785714285
      break
    if case(9): #October
      p7 = 0.01785714285
      break
    if case(10): #November
      p7 = 0.015625
      break
    if case(11): #December
      p7 = 0.01369863013
      break

Day = int(input("The number of the day? "))-1

for case in switch(Day):
    if case(0): #Sunday
      p8 = 0.02083333333
      break
    if case(1): #Monday
      p8 = 0.01492537313
      break
    if case(2): #Tuesday
      p8 = 0.01265822784
      break
    if case(3): #Wednesday
      p8 = 0.01265822784
      break
    if case(4): #Thursday
      p8 = 0.01492537313
      break
    if case(5): #Friday
      p8 = 0.01724137931
      break
    if case(6): #Saturday
      p8 = 0.02173913043
      break

Time = int(input("Time of day? "))

for case in switch(Time):
    if case(0): #Midnight - 3 a.m.
      p9 = 0.01694915254
      break
    if case(1): #3 a.m. - 6 a.m.
      p9 = 0.01052631578
      break
    if case(2): #6 a.m. - 9 a.m.
      p9 = 0.01449275362
      break
    if case(3): #9 a.m. - noon
      p9 = 0.01052631578
      break
    if case(4): #Noon - 3 p.m.
      p9 = 0.01449275362
      break
    if case(5): #3 p.m. - 6 p.m.
      p9 = 0.01960784313
      break
    if case(6): #6 p.m. - 9 p.m.
      p9 = 0.0238095238
      break
    if case(7): #9 p.m. - midnight
      p9 = 0.02083333333
      break

Gend = int(input("Gender? (0 - Men, 1 - Women) "))

for case in switch(Gend):
    if case(0): #Men
      p10 = 0
      break
    if case(1): #Women
      p10 = 0.00819672131
      break

Age = int(input("Age? (0 - over 20, 1 - under 20) "))

for case in switch(Age):
    if case(0): # Over 20 years old
      p11 = 0.00546448087
      break
    if case(1): #(Teens ages 15 - 19
      p11 = 0.01639344262
      break

Grade = (Alc_Grade + Pass_Grade + RD_Grade + Speed_Grade + TXT_Grade + Seat_Grade)/6
Red_Grade = (Alc_Grade + TXT_Grade)/2
#Grade = 4; #Not important part, can be deleted to save memory
#Red_Grade = 2; #Not important part, can be deleted to save memory
#print('Grade - ', Grade) #Not important part, can be deleted to save memory
#print('Red Grade - ', Red_Grade) #Not important part, can be deleted to save memory
if Grade > (Red_Grade + 1):
  Grade = Red_Grade + 1
#print('Grade - ', Grade) #Not important part, can be deleted to save memory
#print('Red Grade - ', Red_Grade) #Not important part, can be deleted to save memory

#Grade = 3.5 #Not important part, can be deleted to save memory
#Red_Grade = 4 #Not important part, can be deleted to save memory
GradeInt = int(Grade)
Grade2 = Grade - GradeInt
#print('GradeInt = ', GradeInt) #Not important part, can be deleted to save memory
#print('Grade2 = ', Grade2) #Not important part, can be deleted to save memory
if Grade2 <=0.40: 
  Grade = Grade - Grade2
elif Grade2 >=0.70: 
  Grade = (Grade - Grade2) + 1
else: 
  if Grade < Red_Grade:
    Grade = (Grade - Grade2) + 1
  elif Grade > Red_Grade:
    Grade = Grade - Grade2
  else:
    if Grade2 >= 0.5:
      Grade = (Grade - Grade2) + 1
    elif Grade2 < 0.5:
      Grade = Grade - Grade2
#print('grade = ', Grade) #Not important part, can be deleted to save memory

for case in switch(Grade):
    if case(0): 
      Res = 'FX'
      break
    if case(1): 
      Res = 'D'
      break
    if case(2): 
      Res = 'C'
      break
    if case(3): 
      Res = 'B'
      break
    if case(4): 
      Res = 'A'
      break
print('Result = ', Res) #Not important part, can be deleted to save memory

q1 = 1-p1
q2 = 1-p2
q3 = 1-p3
q4 = 1-p4
q5 = 1-p5
q6 = 1-p6
q7 = 1-p7
q8 = 1-p8
q9 = 1-p9
q10 = 1-p10
q11 = 1-p11

p = 1-(q1*q2*q3*q4*q5*q6*q7*q8*q9*q10*q11)
p_2 = p-0.01639344262
print('You grade - ', Res)
print('Your chance of getting into an accident: ', p)
print('This is on ', p_2, ' greater than the chance of an accident under normal conditions')